---
## See Also https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- hosts: all
  become: yes  # Run tasks with root/sudo privileges
  become_method: sudo

  tasks:
  - name: Create Sudo/Admin user 'jdoe-sa' and generate RSA SSH key
    ansible.builtin.user:
      name: jdoe-sa
      comment: John Doe
      groups: sudo
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Create regular user 'jsmith' and generate RSA SSH key
    ansible.builtin.user:
      name: jsmith
      comment: John Smith
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

